### ISSUE TITLE
Wrong titles on some videos

### ISSUE THREAD

**Issue by wesley9946** [pcouy/YoutubeAutotranslateCanceler#9]
Hi there,

Sometimes it happens that some videos have the wrong title and thumbnail.
For example: It has the title of Radio Ga Ga by Queen, but it has the thumbnail of one of George Michael's songs and says it's on George Michael's channel.

Can you fix it?

**Comment by wesley9946** [comment]
bump

**Comment by pcouy** [comment]
Sorry, I did not have time to fix this bug. I am aware of it, and have tried to identify the cause, but I don't understand why it happens.
You'll be the first to know when a fix is available.

**Comment by Seneral** [comment]
Am on it, but it's pretty weird. I logged what the script sees when first searching the page, and then of course later. On the first run it definitely sees some older videos, which are then queried with the API but then when the times has come to replace the titles, the underlying titles on the page have changed.
Some titles that have been on the page previously and after the change are correct, all others have titles associated with the videos that have been at their exact spot before the change.

Now why the videos change, idk yet. Either it's youtube shuffling them / changing it's mind or they have not YET been changed from the PPREVIOUS page (most likely). There's a similar problem with the description that I already fixed, so we might need to find out for how long the page has changed and maybe wait until youtube has finished loading.

Or, probably the best alternative, do a first load as we do now but then on the second iteration after page load (1 second) reset the whole thing and reload ALL titles again. That would mean double the work but that's not an issue, double the API requests (meh) but both immediate response and in those rare cases, correction 1 second after loading.

What do you think?

EDIT: Verified it's old videos not yet replaced by youtube, so the script is reacting too fast on load and should either wait until youtube is finished or do a second iteration. Will implement that for now, it's probably the best...

**Comment by Seneral** [comment]
Ok, one iteration is not enough. Rarely I get the case that the top half of the recommended videos list is correct, the bottom still showing wrong titles, and when logging, it shows that even 1 second after page change they STILL have the old video id, which youtube then goes on to replace by the new one afterwards.
So either another full iteration or we need to make some fancy progressive stuff and tracking each element individually.
Or, probably best, checking the video BEFORE replacing if the ID is still the same. If not, check if the new ID is already loaded and use that. Again if not, remove the link element from the alreadyChanged list and make a flag to repeat the whole procedure IMMEDIATELY after finishing the last - that will then start an API request with only the freshly replaced once...

**Comment by Seneral** [comment]
Pretty sure it's fixed now:) Spend a few minutes browsing through international content and could verify all translations that were made.
